spring:
  application:
    name: gym_app_service
  datasource:
    url: jdbc:postgresql://pg-db-2.cyjlsdyq5qfv.us-east-1.rds.amazonaws.com:5432/egym
    username: postgres
    password: mPiTo7ClUVFITw2YF08Q
    driver-class-name: org.postgresql.Driver
  #  flyway:
#    baselineOnMigrate: true
#    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080